# Site settings
permalink: /:year/:month/:title/
paginate: 5
title: jerme
tagline: 'Code Musings'
keywords: software,engineering,functional,programming,lisp
description: > # this means to ignore newlines until "baseurl:"
  I like dabbling with Lisp. Emacs is the one true editor.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jaerme.github.io" # the base hostname & protocol for your site

author:
  name: 'Jeremy Anthony Lee'
  email: jalee453[at]gmail.com
  twitter_username: jerme111
  github_username:  jaerme
  #linkedin_username: jalee453
  #stackoverflow_username: jerme

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
gems:
  - jekyll-paginate
  - jekyll-gist
